
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 21 17:55:39 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 19;
  public static final int KOREN = 48;
  public static final int GE = 42;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 33;
  public static final int FOR = 34;
  public static final int MINUS = 22;
  public static final int RPAREN = 7;
  public static final int AND = 36;
  public static final int LT = 39;
  public static final int OR = 35;
  public static final int UPITNIK = 46;
  public static final int COMMA = 8;
  public static final int DIV = 24;
  public static final int PLUS = 11;
  public static final int IF = 16;
  public static final int LE = 41;
  public static final int TARABA = 47;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 20;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int TRUE = 27;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int NUMBER = 14;
  public static final int MOD = 25;
  public static final int CONSTANT = 43;
  public static final int BREAK = 32;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int LBRACE = 3;
  public static final int ELSE = 17;
  public static final int LSQUARE = 29;
  public static final int ENUM = 44;
  public static final int POINT = 31;
  public static final int READ = 21;
  public static final int RSQUARE = 30;
  public static final int CHARCONST = 18;
  public static final int NOTEQU = 38;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DVETACKE = 45;
  public static final int FALSE = 26;
  public static final int GT = 40;
  public static final int PRINT = 9;
  public static final int EQUEQU = 37;
}

